//	(c) 2003 BEA Systems, Inc. All Rights Reserved. 
//--------------------------------------------------------------------
//
// univo_i.h
//
// Declares the C++ servant implementations for the university
// sample declaration.
//
// Classes declared :
//
//   CourseSynopsisEnumerator_i
//   Registrar_i
//   RegistrarFactory_i
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _univo_i_h
#define _univo_i_h

//--------------------------------------------------------------------

#include <samplesdb.h>
#include "univo_s.h"

//--------------------------------------------------------------------

class CourseSynopsisEnumerator_i :
    public POA_UniversityO::CourseSynopsisEnumerator
{
  public:

    CourseSynopsisEnumerator_i(Database& db);

    virtual ~CourseSynopsisEnumerator_i();

    virtual void destroy();

    virtual void
    activate_object(
        const char* object_id
    );

    virtual UniversityO::CourseSynopsisList*
    get_next_n(
        CORBA::ULong     number_to_get,
        CORBA::ULong_out number_remaining
    );

  private:
     Database&                       m_db;
     UniversityO::CourseSynopsisList m_matches;
     CORBA::ULong                    m_index;
};

//--------------------------------------------------------------------

class Registrar_i :
    public POA_UniversityO::Registrar
{
  public:

    Registrar_i(
        Database& db
    );

    virtual ~Registrar_i();


    virtual UniversityO::CourseSynopsisList*
    get_courses_synopsis(
        const char*                               search_criteria,
        CORBA::ULong                              number_to_get,
        CORBA::ULong_out                          number_remaining,
        UniversityO::CourseSynopsisEnumerator_out rest
    );

    virtual UniversityO::Courses*
    get_courses(
         const UniversityO::CourseNumberList& courses
    );

  private:
    Database& m_db;
};

//--------------------------------------------------------------------

class RegistrarFactory_i :
    public POA_UniversityO::RegistrarFactory
{
  public:
    RegistrarFactory_i();

    virtual ~RegistrarFactory_i();

    virtual UniversityO::Registrar_ptr find_registrar(
    );
};

//--------------------------------------------------------------------

#endif
