//	(c) 2003 BEA Systems, Inc. All Rights Reserved. 
//--------------------------------------------------------------------
//
// univt_i.h
//
// Declares the C++ servant implementations for the university
// sample declaration.
//
// Classes declared :
//
//   CourseSynopsisEnumerator_i
//   Registrar_i
//   RegistrarFactory_i
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _univt_i_h
#define _univt_i_h

//--------------------------------------------------------------------

#include <samplesdb.h>
#include "univt_s.h"

//--------------------------------------------------------------------

class CourseSynopsisEnumerator_i :
    public POA_UniversityT::CourseSynopsisEnumerator
{
  public:

    CourseSynopsisEnumerator_i(Database& db);

    virtual ~CourseSynopsisEnumerator_i();

    virtual void destroy();

    virtual void
    activate_object(
        const char* object_id
    );

    virtual UniversityT::CourseSynopsisList*
    get_next_n(
        CORBA::ULong     number_to_get,
        CORBA::ULong_out number_remaining
    );

  private:
     Database&                       m_db;
     UniversityT::CourseSynopsisList m_matches;
     CORBA::ULong                    m_index;
};

//--------------------------------------------------------------------

class Registrar_i :
    public POA_UniversityT::Registrar
{
  public:

    Registrar_i(
        Database& db
    );

    virtual ~Registrar_i();


    virtual UniversityT::CourseSynopsisList*
    get_courses_synopsis(
        const char*                               search_criteria,
        CORBA::ULong                              number_to_get,
        CORBA::ULong_out                          number_remaining,
        UniversityT::CourseSynopsisEnumerator_out rest
    );

    virtual UniversityT::CourseDetailsList*
    get_courses_details(
         const UniversityT::CourseNumberList& courses
    );

    virtual UniversityT::StudentDetails*
    get_student_details(
        UniversityT::StudentId student
    );

    virtual UniversityT::NotRegisteredList*
    register_for_courses(
        UniversityT::StudentId               student,
        const UniversityT::CourseNumberList& courses
    );

  private:
    Database& m_db;
};

//--------------------------------------------------------------------

class RegistrarFactory_i :
    public POA_UniversityT::RegistrarFactory
{
  public:
    RegistrarFactory_i();

    virtual ~RegistrarFactory_i();

    virtual UniversityT::Registrar_ptr find_registrar(
    );
};

//--------------------------------------------------------------------

#endif
