//      Copyright (c) 2001 BEA Systems, Inc.
//      All rights reserved
//
//      THIS IS UNPUBLISHED PROPRIETARY
//      SOURCE CODE OF BEA Systems, Inc.
//      The copyright notice above does not
//      evidence any actual or intended
//      publication of such source code.
//

#ifndef __ORB__
#define __ORB__

#pragma prefix "omg.org"

module CORBA
{
	valuetype StringValue string;
	valuetype WStringValue wstring;
};

#endif
