//	(c) 2003 BEA Systems, Inc. All Rights Reserved. 
//--------------------------------------------------------------------
//
// univb_i.h
//
// Declares the C++ servant implementations for the university
// sample declaration.
//
// Classes declared :
//
//   CourseSynopsisEnumerator_i
//   Registrar_i
//   RegistrarFactory_i
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _univb_i_h
#define _univb_i_h

//--------------------------------------------------------------------

#include <samplesdb.h>
#include "univb_s.h"

//--------------------------------------------------------------------

class CourseSynopsisEnumerator_i :
    public POA_UniversityB::CourseSynopsisEnumerator
{
  public:

    CourseSynopsisEnumerator_i(Database& db);

    virtual ~CourseSynopsisEnumerator_i();

    virtual void destroy();

    virtual void
    activate_object(
        const char* object_id
    );

    virtual UniversityB::CourseSynopsisList*
    get_next_n(
        CORBA::ULong     number_to_get,
        CORBA::ULong_out number_remaining
    );

  private:
     Database&                       m_db;
     UniversityB::CourseSynopsisList m_matches;
     CORBA::ULong                    m_index;
};

//--------------------------------------------------------------------

class Registrar_i :
    public POA_UniversityB::Registrar
{
  public:

    Registrar_i(
        Database& db
    );

    virtual ~Registrar_i();


    virtual UniversityB::CourseSynopsisList*
    get_courses_synopsis(
        const char*                               search_criteria,
        CORBA::ULong                              number_to_get,
        CORBA::ULong_out                          number_remaining,
        UniversityB::CourseSynopsisEnumerator_out rest
    );

    virtual UniversityB::CourseDetailsList*
    get_courses_details(
         const UniversityB::CourseNumberList& courses
    );

  private:
    Database& m_db;
};

//--------------------------------------------------------------------

class RegistrarFactory_i :
    public POA_UniversityB::RegistrarFactory
{
  public:
    RegistrarFactory_i();

    virtual ~RegistrarFactory_i();

    virtual UniversityB::Registrar_ptr find_registrar(
    );
};

//--------------------------------------------------------------------

#endif
