/*	(c) 2003 BEA Systems, Inc. All Rights Reserved. */
/*	Copyright (c) 1997 BEA Systems, Inc.
  	All rights reserved

  	THIS IS UNPUBLISHED PROPRIETARY
  	SOURCE CODE OF BEA Systems, Inc.
  	The copyright notice above does not
  	evidence any actual or intended
  	publication of such source code.
*/

/* Copyright (c) 1994 Novell Inc. */

/* #ident	"@(#) samples/atmi/rpcsimp/dceepv.c	$Revision: 1.5 $" */

#include <simpdce.h>		/* header generated by IDL compiler */
#include <dce/rpcexc.h>		/* RAISE macro */

static void myto_upper(rpc_binding_handle_t hdl, idl_char *str);
static void myto_lower(rpc_binding_handle_t hdl, idl_char *str);

/*
 * A manager entry point vector is defined so that we can generate
 * a valid DCE binding handle to go to the DCE server.
 * Note that the input handle to entry point functions will always
 * be NULL since TUXEDO TxRPC doesn't support handles.
 */

/* Manager entry point vector with two operations */
changecase_v1_0_epv_t changecase_v1_0_s_epv = {
	myto_upper,
	myto_lower
};

int dobind(rpc_binding_handle_t *hdl);

static void
myto_upper(rpc_binding_handle_t hdl, idl_char *str)
{
	rpc_binding_handle_t handle;
	if (dobind(&handle) < 0) {	/* get binding handle for server */
		userlog("binding failed");
		RAISE(rpc_x_invalid_binding);
	}
	to_upper(handle, str);		/* call DCE client stub */
}

static void
myto_lower(rpc_binding_handle_t hdl, idl_char *str)
{
	rpc_binding_handle_t handle;
	if (dobind(&handle) < 0) {	/* get binding handle for server */
		userlog("binding failed");
		RAISE(rpc_x_invalid_binding);
	}
	to_lower(handle, str);		/* call DCE client stub */
}
