/*	(c) 2003 BEA Systems, Inc. All Rights Reserved. */
/*	Copyright (c) 1997 BEA Systems, Inc.
  	All rights reserved

  	THIS IS UNPUBLISHED PROPRIETARY
  	SOURCE CODE OF BEA Systems, Inc.
  	The copyright notice above does not
  	evidence any actual or intended
  	publication of such source code.
*/

/* Copyright (c) 1994 Novell Inc. */

/* #ident	"@(#) samples/atmi/rpcsimp/dcemgr.c	$Revision: 1.5 $" */

#include <stdio.h>
#include <ctype.h>

#include "simpdce.h"		/* header generated by IDL compiler */
#include <dce/rpcexc.h>		/* RAISE macro */
#include <dce/dce_error.h>	/* required to call dce_error_inq_text */
#include <dce/binding.h>	/* binding to registry */
#include <dce/pgo.h>		/* registry i/f */
#include <dce/secidmap.h>	/* translate global name -> princ name */


void
checkauth(rpc_binding_handle_t handle)
{
	int error_stat;
	static unsigned char error_string[dce_c_error_string_len];
	sec_id_pac_t	*pac;			/* client pac */
	unsigned_char_t	*server_principal_name;	/* requested server principal */
	unsigned32	protection_level;	/* protection level */
	unsigned32	authn_svc;		/* authentication service */
	unsigned32	authz_svc;		/* authorization service */
	sec_rgy_handle_t rgy_handle;
	error_status_t	status;

	/*
	 * Check the authentication parameters that the client
	 * selected for this call.
	 */
	rpc_binding_inq_auth_client(
		handle,			/* input handle */
		(rpc_authz_handle_t *)&pac,	/* returned client pac */
		&server_principal_name,	/* returned requested server princ */
		&protection_level,	/* returned protection level */
		&authn_svc,		/* returned authentication service */
		&authz_svc,		/* returned authorization service */
		&status);
	if (status != rpc_s_ok) {
		dce_error_inq_text(status, error_string, &error_stat);
		fprintf(stderr, "%s %s\n", "inq_auth_client failed",
			error_string);
		RAISE(rpc_x_invalid_binding);
		return;
	}

	/*
	 * Make sure that the caller has specified the required
	 * level of protection, authentication, and authorization.
	 */
	if (protection_level != rpc_c_protect_level_pkt_integ ||
	    authn_svc != rpc_c_authn_dce_secret ||
	    authz_svc != rpc_c_authz_dce) {
		fprintf(stderr, "not authorized");
		RAISE(rpc_x_invalid_binding);
		return;
	}

	return;
}

void
to_upper(rpc_binding_handle_t handle, idl_char *str)
{
	idl_char *p;

	checkauth(handle);

	/* Any ACL or reference monitor checking could be done here */

	/* Convert to upper case */
	for (p=str; *p != '\0'; p++)
		*p = toupper((int)*p);
	return;
}


void
to_lower(rpc_binding_handle_t handle, idl_char *str)
{
	idl_char *p;

	checkauth(handle);

	/* Any ACL or reference monitor checking could be done here */


	/* Convert to lower case */
	for (p=str; *p != '\0'; p++)
		*p = tolower((int)*p);
	return;
}
