#---------------------------------------------------------------------
#	(c) 2003 BEA Systems, Inc. All Rights Reserved.
#
# common.mk
#
# Unix makefile fragment which defines makefile symbols used by
# the various notification samples.  These symbols allow the Unix
# and Windows makefiles to delegate the build rules to platform
# independent makefiles.
#
# BEA Systems Inc. sample code
#
#---------------------------------------------------------------------

# common symbols
PERCENT     =%#      a literal % character
DQUOTE      =\"#     a literal " character
SLASH       =/#      the directory separator character for pathnames
SEPARATOR   =:#      the directory separator character for classpaths
SHEXT       =.ksh#   the file extension for scripts
RM          =rm -f#  remove a file
RMDIR       =rm -rf# recursively remove a directory
NOOPCMD     =true#   run a command that does nothing

# C++ symbols
EXEEXT      =#       the file extension for executables
TEMP_FILES  =*.o#    files generated by the build that must be cleaned up
PRELIB      =-l#     text to include before linking in a library
POSTLIB     =#       text to include after  linking in a library
EXTRAFLAGS  =#       extra C++ compiler flags

# Java symbols
CREATE      =touch#  create a new file
