//	(c) 2003 BEA Systems, Inc. All Rights Reserved. 
//--------------------------------------------------------------------
//
// univw_i.h
//
// Declares the C++ servant implementations for the university
// sample declaration.
//
// Classes declared :
//
//   CourseSynopsisEnumerator_i
//   Registrar_i
//   RegistrarFactory_i
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _univw_i_h
#define _univw_i_h

//--------------------------------------------------------------------

#include <samplesdb.h>
#include "billw_c.h"
#include "univw_s.h"

//--------------------------------------------------------------------

class CourseSynopsisEnumerator_i :
    public POA_UniversityW::CourseSynopsisEnumerator
{
  public:

    CourseSynopsisEnumerator_i(
        Database& db
    );

    virtual ~CourseSynopsisEnumerator_i();

    virtual void destroy();

    virtual void
    activate_object(
        const char* object_id
    );

    virtual UniversityW::CourseSynopsisList*
    get_next_n(
        CORBA::ULong     number_to_get,
        CORBA::ULong_out number_remaining
    );

  private:
     Database&                       m_db;
     UniversityW::CourseSynopsisList m_matches;
     CORBA::ULong                    m_index;
};

//--------------------------------------------------------------------

class Registrar_i :
    public POA_UniversityW::Registrar
{
  public:

    Registrar_i(
        Database&                   db,
        BillingW::TellerFactory_ptr p_tell_fact_ref
    );

    virtual ~Registrar_i();


    virtual UniversityW::CourseSynopsisList*
    get_courses_synopsis(
        const char*                               search_criteria,
        CORBA::ULong                              number_to_get,
        CORBA::ULong_out                          number_remaining,
        UniversityW::CourseSynopsisEnumerator_out rest
    );

    virtual UniversityW::CourseDetailsList*
    get_courses_details(
         const UniversityW::CourseNumberList& courses
    );

    virtual UniversityW::StudentDetails*
    get_student_details(
        UniversityW::StudentId student
    );

    virtual UniversityW::NotRegisteredList*
    register_for_courses(
        UniversityW::StudentId               student,
        const UniversityW::CourseNumberList& courses
    );

  private:
    Database&                   m_db;
    BillingW::TellerFactory_ptr m_p_tell_fact_ref;
};

//--------------------------------------------------------------------

class RegistrarFactory_i :
    public POA_UniversityW::RegistrarFactory
{
  public:
    RegistrarFactory_i();

    virtual ~RegistrarFactory_i();

    virtual UniversityW::Registrar_ptr find_registrar();
};

//--------------------------------------------------------------------

#endif
