//--------------------------------------------------------------------
//	(c) 2003 BEA Systems, Inc. All Rights Reserved.
//
// simple_i.h
//
// C++ servant declarations for the simple sample declaration.
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _simple_i_h
#define _simple_i_h

#include "simple_s.h"
extern char* generate_unique_id();           // Generate unique uuids

class Simple_i : public POA_Simple
{
  public:
    virtual wchar_t* to_lower(const wchar_t* val);
    virtual void  to_upper(wchar_t*&      val);
};

class SimpleFactory_i : public POA_SimpleFactory
{
  public:
    virtual Simple_ptr find_simple();

    // To make simpapp scalable have the SimpleFactory use the user
    // supplied identifier in the Simple object reference it creates.
};

#endif
