/*	(c) 2003 BEA Systems, Inc. All Rights Reserved. */
/**
 *This is the BEA Iceberg sample UniversityApplet.
 *
 */

import java.awt.*;
import java.applet.*;
import java.net.*;
import com.beasys.Tobj.*;
import com.beasys.*;
import org.omg.*;
import UniversityS.*;

public class UnivSApplet extends java.applet.Applet 
{

    UniversityS.CourseSynopsis[] gCourseSynopsis;
    UniversityS.CourseDetails[] gCourseDetailsFromSrvr;
    UniversityS.Registrar gRegistrarObjRef;
    UniversityS.StudentDetails gStudentDetails;
    Tobj_Bootstrap gBootstrapObjRef = null;
    final private static int _TMMAXPASSLEN = 8;
    com.beasys.Tobj.PrincipalAuthenticator gPrinAuthObjRef = null;
    String gUserId = null;
    String gSystemPassword = "";
    String gUserPassword = "";

    // This keeps track of where we are in the Course Details list
    int gCurrentDetailsIndex = -1;

    Color gPurpleColor = new Color(133,2,166); //8716966
    Color gLightGrayColor = new Color(221,221,221);
    Color gGrayColor = new Color(200,200,200);    

    public void init()
    {
        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parse your Java file into its visual environment.
        //{{INIT_CONTROLS
		setLayout(null);
		setSize(371,287);
		setBackground(new Color(16777215));
		SynopsisPanel = new java.awt.Panel();
		SynopsisPanel.setLayout(null);
		SynopsisPanel.setBounds(384,0,372,264);
		SynopsisPanel.setForeground(new Color(-8060250));
		SynopsisPanel.setBackground(new Color(12632256));
		add(SynopsisPanel);
		SynopsisCriteriaLabel = new java.awt.Label("Course name search string?");
		SynopsisCriteriaLabel.setBounds(12,12,252,24);
		SynopsisCriteriaLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		SynopsisCriteriaLabel.setForeground(new Color(-8060250));
		SynopsisPanel.add(SynopsisCriteriaLabel);
		SynopsisShowBtn = new java.awt.Button();
		SynopsisShowBtn.setActionCommand("button");
		SynopsisShowBtn.setLabel("Show");
		SynopsisShowBtn.setBounds(288,36,60,24);
		SynopsisShowBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		SynopsisShowBtn.setForeground(new Color(-8060250));
		SynopsisPanel.add(SynopsisShowBtn);
		SynopsisShowBtn.setEnabled(false);
		SynopsisDetailsBtn = new java.awt.Button();
		SynopsisDetailsBtn.setActionCommand("button");
		SynopsisDetailsBtn.setLabel("Details");
		SynopsisDetailsBtn.setBounds(156,228,60,28);
		SynopsisDetailsBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		SynopsisDetailsBtn.setForeground(new Color(-8060250));
		SynopsisPanel.add(SynopsisDetailsBtn);
		SynopsisDetailsBtn.setEnabled(false);
		SynopsisCriteriaTextFld = new java.awt.TextField();
		SynopsisCriteriaTextFld.setBounds(12,36,264,24);
		SynopsisPanel.add(SynopsisCriteriaTextFld);
		SynopsisCourseList = new java.awt.List(0,false);
		SynopsisPanel.add(SynopsisCourseList);
		SynopsisCourseList.setBounds(12,108,336,108);
		SynopsisCourseList.setBackground(new Color(-2236963));
		SynopsisCourseList.setEnabled(false);
		SynopsisHeadingPanel = new java.awt.Panel();
		SynopsisHeadingPanel.setLayout(null);
		SynopsisHeadingPanel.setBounds(12,60,324,40);
		SynopsisPanel.add(SynopsisHeadingPanel);
		SynopsisHeadingNumLabel = new java.awt.Label("Course Number");
		SynopsisHeadingNumLabel.setBounds(0,24,103,23);
		SynopsisHeadingNumLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		SynopsisHeadingNumLabel.setForeground(new Color(-8060250));
		SynopsisHeadingPanel.add(SynopsisHeadingNumLabel);
		SynopsisHeadingNameLabel = new java.awt.Label("Course Name");
		SynopsisHeadingNameLabel.setBounds(144,24,91,23);
		SynopsisHeadingNameLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		SynopsisHeadingNameLabel.setForeground(new Color(-8060250));
		SynopsisHeadingPanel.add(SynopsisHeadingNameLabel);
		SynopsisLogOffBtn = new java.awt.Button();
		SynopsisLogOffBtn.setActionCommand("button");
		SynopsisLogOffBtn.setLabel("LogOff");
		SynopsisLogOffBtn.setBounds(48,228,60,28);
		SynopsisLogOffBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		SynopsisLogOffBtn.setBackground(new Color(12632256));
		SynopsisPanel.add(SynopsisLogOffBtn);
		DetailsPanel = new java.awt.Panel();
		DetailsPanel.setLayout(null);
		DetailsPanel.setVisible(false);
		DetailsPanel.setBounds(408,300,372,264);
		DetailsPanel.setForeground(new Color(-8060250));
		DetailsPanel.setBackground(new Color(12632256));
		add(DetailsPanel);
		DetailsPrevBtn = new java.awt.Button();
		DetailsPrevBtn.setActionCommand("button");
		DetailsPrevBtn.setLabel("Previous");
		DetailsPrevBtn.setBounds(23,227,86,28);
		DetailsPrevBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsPanel.add(DetailsPrevBtn);
		DetailsNextBtn = new java.awt.Button();
		DetailsNextBtn.setActionCommand("button");
		DetailsNextBtn.setLabel("Next");
		DetailsNextBtn.setBounds(263,227,86,28);
		DetailsNextBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsPanel.add(DetailsNextBtn);
		DetailsCloseBtn = new java.awt.Button();
		DetailsCloseBtn.setActionCommand("button");
		DetailsCloseBtn.setLabel("Close");
		DetailsCloseBtn.setBounds(155,227,72,28);
		DetailsCloseBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsPanel.add(DetailsCloseBtn);
		DetailsDescPanel = new java.awt.Panel();
		DetailsDescPanel.setLayout(null);
		DetailsDescPanel.setBounds(11,107,336,108);
		DetailsPanel.add(DetailsDescPanel);
		DetailsDescLabel = new java.awt.Label("Desc:",Label.RIGHT);
		DetailsDescLabel.setBounds(0,4,36,16);
		DetailsDescLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsDescPanel.add(DetailsDescLabel);
		DetailsDescTextArea = new java.awt.TextArea("",0,48,TextArea.SCROLLBARS_VERTICAL_ONLY);
		DetailsDescTextArea.setEditable(false);
		DetailsDescTextArea.setBounds(48,0,290,108);
		DetailsDescTextArea.setBackground(new Color(-2236963));
		DetailsDescPanel.add(DetailsDescTextArea);
		DetailsInfoPanel = new java.awt.Panel();
		DetailsInfoPanel.setLayout(null);
		DetailsInfoPanel.setBounds(0,12,384,84);
		DetailsInfoPanel.setBackground(new Color(12632256));
		DetailsPanel.add(DetailsInfoPanel);
		DetailsInfoIdLabel = new java.awt.Label("Id:",Label.RIGHT);
		DetailsInfoIdLabel.setBounds(11,-1,36,12);
		DetailsInfoIdLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoIdLabel);
		DetailsInfoIdValueLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoIdValueLabel.setBounds(59,-1,48,12);
		DetailsInfoIdValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoIdValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoIdValueLabel);
		DetailsInfoProfessorLabel = new java.awt.Label("Prof:",Label.RIGHT);
		DetailsInfoProfessorLabel.setBounds(131,-1,36,12);
		DetailsInfoProfessorLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoProfessorLabel);
		DetailsInfoProfessorValueLabel = new java.awt.Label("");
		DetailsInfoProfessorValueLabel.setBounds(179,-1,168,12);
		DetailsInfoProfessorValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoProfessorValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoProfessorValueLabel);
		DetailsInfoCreditsLabel = new java.awt.Label("Credits:",Label.RIGHT);
		DetailsInfoCreditsLabel.setBounds(144,48,48,12);
		DetailsInfoCreditsLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoCreditsLabel);
		DetailsInfoCreditsValueLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoCreditsValueLabel.setBounds(204,47,36,13);
		DetailsInfoCreditsValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoCreditsValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoCreditsValueLabel);
		DetailsInfoCostLabel = new java.awt.Label("Cost:",Label.RIGHT);
		DetailsInfoCostLabel.setBounds(11,47,36,12);
		DetailsInfoCostLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoCostLabel);
		DetailsInfoCostValueLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoCostValueLabel.setBounds(59,47,61,13);
		DetailsInfoCostValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoCostValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoCostValueLabel);
		DetailsInfoOpenLabel = new java.awt.Label("Open:",Label.RIGHT);
		DetailsInfoOpenLabel.setBounds(239,47,48,12);
		DetailsInfoOpenLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoOpenLabel);
		DetailsInfoOpenValueLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoOpenValueLabel.setBounds(299,47,48,12);
		DetailsInfoOpenValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoOpenValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoOpenValueLabel);
		DetailsInfoTitleLabel = new java.awt.Label("Title:",Label.RIGHT);
		DetailsInfoTitleLabel.setBounds(11,23,36,12);
		DetailsInfoTitleLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoTitleLabel);
		DetailsInfoTitleValueLabel = new java.awt.Label("");
		DetailsInfoTitleValueLabel.setBounds(59,23,288,12);
		DetailsInfoTitleValueLabel.setFont(new Font("Dialog", Font.PLAIN, 12));
		DetailsInfoTitleValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoTitleValueLabel);
		DetailsInfoSchedLabel = new java.awt.Label("Start:");
		DetailsInfoSchedLabel.setBounds(11,71,47,17);
		DetailsInfoSchedLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoSchedLabel);
		DetailsInfoSchedTimeLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoSchedTimeLabel.setBounds(60,72,36,12);
		DetailsInfoSchedTimeLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoSchedTimeLabel);
		DetailsInfoMonLabel = new java.awt.Label("Mon",Label.CENTER);
		DetailsInfoMonLabel.setBounds(228,72,24,12);
		DetailsInfoMonLabel.setForeground(new Color(-5592406));
		DetailsInfoMonLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoMonLabel);
		DetailsInfoTueLabel = new java.awt.Label("Tue",Label.CENTER);
		DetailsInfoTueLabel.setBounds(252,72,24,12);
		DetailsInfoTueLabel.setForeground(new Color(-5592406));
		DetailsInfoTueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoTueLabel);
		DetailsInfoWedLabel = new java.awt.Label("Wed",Label.CENTER);
		DetailsInfoWedLabel.setBounds(276,72,24,12);
		DetailsInfoWedLabel.setForeground(new Color(-5592406));
		DetailsInfoWedLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoWedLabel);
		DetailsInfoThuLabel = new java.awt.Label("Thu",Label.CENTER);
		DetailsInfoThuLabel.setBounds(300,72,24,12);
		DetailsInfoThuLabel.setForeground(new Color(-5592406));
		DetailsInfoThuLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoThuLabel);
		DetailsInfoFriLabel = new java.awt.Label("Fri",Label.CENTER);
		DetailsInfoFriLabel.setBounds(324,72,24,12);
		DetailsInfoFriLabel.setForeground(new Color(-5592406));
		DetailsInfoFriLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoFriLabel);
		DetailsInfoDurationValueLabel = new java.awt.Label("",Label.RIGHT);
		DetailsInfoDurationValueLabel.setBounds(180,72,36,12);
		DetailsInfoDurationValueLabel.setBackground(new Color(-2236963));
		DetailsInfoPanel.add(DetailsInfoDurationValueLabel);
		DetailsInfoDurationLabel = new java.awt.Label("Duration:");
		DetailsInfoDurationLabel.setBounds(120,71,59,17);
		DetailsInfoDurationLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		DetailsInfoPanel.add(DetailsInfoDurationLabel);
		InitializingLabel = new java.awt.Label("Initializing...",Label.CENTER);
		InitializingLabel.setVisible(false);
		InitializingLabel.setBounds(828,300,120,24);
		InitializingLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		InitializingLabel.setForeground(new Color(-8060250));
		add(InitializingLabel);
		LogOnLabel = new java.awt.Label("Logging On...",Label.CENTER);
		LogOnLabel.setVisible(false);
		LogOnLabel.setBounds(828,264,120,24);
		LogOnLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		LogOnLabel.setForeground(new Color(-8060250));
		add(LogOnLabel);
		LogPanel = new java.awt.Panel();
		LogPanel.setLayout(null);
		LogPanel.setBounds(0,0,372,264);
		LogPanel.setForeground(new Color(-8060250));
		LogPanel.setBackground(new Color(12632256));
		add(LogPanel);
		LogStudentIdLabel = new java.awt.Label("Student Id",Label.RIGHT);
		LogStudentIdLabel.setBounds(24,108,120,24);
		LogStudentIdLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		LogStudentIdLabel.setForeground(new Color(-8060250));
		LogPanel.add(LogStudentIdLabel);
		LogOnBtn = new java.awt.Button();
		LogOnBtn.setActionCommand("button");
		LogOnBtn.setLabel("LogOn");
		LogOnBtn.setBounds(143,227,60,28);
		LogOnBtn.setFont(new Font("Dialog", Font.BOLD, 12));
		LogOnBtn.setForeground(new Color(-8060250));
		LogPanel.add(LogOnBtn);
		LogOnBtn.setEnabled(false);
		LogStudentIdTextFld = new java.awt.TextField();
		LogStudentIdTextFld.setBounds(156,108,168,24);
		LogPanel.add(LogStudentIdTextFld);
		LogDomainPassLabel = new java.awt.Label("Domain Password",Label.RIGHT);
		LogDomainPassLabel.setBounds(12,144,132,24);
		LogDomainPassLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		LogDomainPassLabel.setForeground(new Color(-8060250));
		LogPanel.add(LogDomainPassLabel);
		LogDomainPassTextFld = new java.awt.TextField();
		LogDomainPassTextFld.setEchoChar('*');
		LogDomainPassTextFld.setBounds(156,144,168,24);
		LogPanel.add(LogDomainPassTextFld);
		LogStudentPassLabel = new java.awt.Label("Student Password",Label.RIGHT);
		LogStudentPassLabel.setBounds(12,180,132,24);
		LogStudentPassLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		LogStudentPassLabel.setForeground(new Color(-8060250));
		LogPanel.add(LogStudentPassLabel);
		LogStudentPassTextFld = new java.awt.TextField();
		LogStudentPassTextFld.setEchoChar('*');
		LogStudentPassTextFld.setBounds(156,180,168,24);
		LogPanel.add(LogStudentPassTextFld);
		LogWelcomeLabel = new java.awt.Label("Welcome",Label.CENTER);
		LogWelcomeLabel.setBounds(48,12,276,48);
		LogWelcomeLabel.setFont(new Font("Dialog", Font.BOLD, 30));
		LogWelcomeLabel.setForeground(new Color(-8060250));
		LogPanel.add(LogWelcomeLabel);
		LogInvalidPassLabel = new java.awt.Label("Invalid Password!  Please re-enter password",Label.CENTER);
		LogInvalidPassLabel.setBounds(12,72,348,24);
		LogInvalidPassLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		LogInvalidPassLabel.setForeground(new Color(16711680));
		LogPanel.add(LogInvalidPassLabel);
		LogInvalidPassLenLabel = new java.awt.Label("Invalid Length! Enter password with 8 or less chars ",Label.CENTER);
		LogInvalidPassLenLabel.setBounds(12,72,348,24);
		LogInvalidPassLenLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		LogInvalidPassLenLabel.setForeground(new Color(16711680));
		LogPanel.add(LogInvalidPassLenLabel);
		LogNonNumericIdLabel = new java.awt.Label("Non-Numeric Id! Please enter a valid numeric Id",Label.CENTER);
		LogNonNumericIdLabel.setBounds(12,72,348,24);
		LogNonNumericIdLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		LogNonNumericIdLabel.setForeground(new Color(16711680));
		LogPanel.add(LogNonNumericIdLabel);
		LogInvalidIdLabel = new java.awt.Label("Invalid Id! Please enter a valid id",Label.CENTER);
		LogInvalidIdLabel.setBounds(12,72,348,24);
		LogInvalidIdLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		LogInvalidIdLabel.setForeground(new Color(16711680));
		LogPanel.add(LogInvalidIdLabel);
		//}}

        //{{REGISTER_LISTENERS
        SymMouse aSymMouse = new SymMouse();
        SynopsisShowBtn.addMouseListener(aSymMouse);
        SynopsisDetailsBtn.addMouseListener(aSymMouse);
        DetailsCloseBtn.addMouseListener(aSymMouse);
        DetailsNextBtn.addMouseListener(aSymMouse);
        DetailsPrevBtn.addMouseListener(aSymMouse);
        SymAction lSymAction = new SymAction();
        SymText lSymText = new SymText();
        SynopsisCriteriaTextFld.addTextListener(lSymText);
        SymItem lSymItem = new SymItem();
        SynopsisCourseList.addItemListener(lSymItem);
        SynopsisCriteriaTextFld.addActionListener(lSymAction);
        SynopsisDetailsBtn.addMouseListener(aSymMouse);
        SynopsisDetailsBtn.addActionListener(lSymAction);
        SymKey aSymKey = new SymKey();
        SynopsisShowBtn.addKeyListener(aSymKey);
        DetailsNextBtn.addKeyListener(aSymKey);
        DetailsPrevBtn.addKeyListener(aSymKey);
        DetailsCloseBtn.addKeyListener(aSymKey);
        LogOnBtn.addMouseListener(aSymMouse);
        LogOnBtn.addKeyListener(aSymKey);
        LogStudentIdTextFld.addTextListener(lSymText);
        LogDomainPassTextFld.addTextListener(lSymText);
        LogStudentPassTextFld.addTextListener(lSymText);
        SynopsisLogOffBtn.addMouseListener(aSymMouse);
        //}}

        SynopsisCourseList.setMultipleMode(true);
        SynopsisCourseList.setForeground(gPurpleColor);
        SynopsisPanel.setVisible(false);
        DetailsPanel.setVisible(false);
        LogInvalidPassLabel.setVisible(false);
        LogInvalidPassLenLabel.setVisible(false);
        LogInvalidIdLabel.setVisible(false);
        LogNonNumericIdLabel.setVisible(false);
        LogPanel.setVisible(false);

        // Display something
        InitializingLabel.setLocation(120,120);
        InitializingLabel.setVisible(true);


        try
        {
            // Initialize ORB
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(this,null);

            int    port = Integer.parseInt(getParameter("port"));
            String    svr = get_default_server();
            if ((svr == null) || (svr.length() == 0))
                svr = getParameter("host");

            String TuxFormatHost = "//" + svr + ':' + port;

            // Create Bootstrap object
            gBootstrapObjRef = new Tobj_Bootstrap(orb, TuxFormatHost);

            // Setup Security
            // Get the Security Current Object
            org.omg.CORBA.Object secCurObj =
                    gBootstrapObjRef.resolve_initial_references( "SecurityCurrent");
            org.omg.SecurityLevel2.Current secCur =
        		org.omg.SecurityLevel2.CurrentHelper.narrow(secCurObj);

            // Get a principalauthenticator
            org.omg.SecurityLevel2.PrincipalAuthenticator authlev2 =
                secCur.principal_authenticator();

            gPrinAuthObjRef = (com.beasys.Tobj.PrincipalAuthenticator)
                org.omg.SecurityLevel2.PrincipalAuthenticatorHelper.narrow(authlev2);

            // Get the auth type
            com.beasys.Tobj.AuthType authType = gPrinAuthObjRef.get_auth_type();
            // Set args according to security level
            switch (authType.value())
            {
                case com.beasys.Tobj.AuthType._TOBJ_NOAUTH:
                    // No passwords need so make all password fields invisible
                    LogDomainPassLabel.setVisible(false);
                    LogDomainPassTextFld.setVisible(false);
                    LogStudentPassLabel.setVisible(false);
                    LogStudentPassTextFld.setVisible(false);
                    break;
                case com.beasys.Tobj.AuthType._TOBJ_SYSAUTH:
                    // Just need a domain password, hide the system
                    // password prompt field
                    LogStudentPassLabel.setVisible(false);
                    LogStudentPassTextFld.setVisible(false);
                    break;
                case com.beasys.Tobj.AuthType._TOBJ_APPAUTH:
                    // Prompt for all passwords, don't have to hide anything
                    break;
            }
            InitializingLabel.setVisible(false);
            LogPanel.setLocation(1,1);
            LogPanel.setVisible(true);
        }
        catch(com.beasys.Tobj.InvalidName e)
        {
            System.err.println("Invalid name: " + e);
            System.exit(1);
        }
        catch(com.beasys.Tobj.InvalidDomain e)
        {
            System.err.println("Invalid Domain " + e);
            System.err.println("Make sure that the university_server is running.");
            System.exit(1);
        }
        catch(org.omg.CORBA.SystemException e)
        {
            System.err.println("System exception " + e);
            System.exit(1);
        }

    }

    void clearLogWarningLabels()
    {
        LogInvalidPassLabel.setVisible(false);
        LogInvalidPassLenLabel.setVisible(false);
        LogInvalidIdLabel.setVisible(false);
        LogNonNumericIdLabel.setVisible(false);
    }

    void log_on ()
    {
        byte[] userData = new byte[0];
        String clientName = "university_client";
            

        LogPanel.setVisible(false);
        LogOnLabel.setLocation(120,120);
        LogOnLabel.setVisible(true);
        
        gUserId = LogStudentIdTextFld.getText();
        try
        {
            int check_id = Integer.parseInt(gUserId);
        }
        catch (java.lang.NumberFormatException e)
        {
            // Need to enter a number for a student id
            LogOnLabel.setVisible(false);
            LogNonNumericIdLabel.setVisible(true);
            LogPanel.setLocation(1,1);
            LogPanel.setVisible(true);
            return;
        }
        gSystemPassword = LogDomainPassTextFld.getText();
        if ( gSystemPassword.length() > _TMMAXPASSLEN)
        {
            LogOnLabel.setVisible(false);
            LogInvalidPassLabel.setVisible(false);
            LogInvalidPassLenLabel.setVisible(true);
            LogPanel.setLocation(1,1);
            LogPanel.setVisible(true);
            return;
        }
        gUserPassword = LogStudentPassTextFld.getText();
        try
        {
            // Perform Tux style logon
            org.omg.Security.AuthenticationStatus status = 
                gPrinAuthObjRef.logon(gUserId, clientName, gSystemPassword,
                    gUserPassword, userData);
            if (status.value() == org.omg.Security.AuthenticationStatus._SecAuthSuccess)
            {
                // We were able to log in
                try
                {
                    // Resolve Factory Finder
                    org.omg.CORBA.Object Off =
                        gBootstrapObjRef.resolve_initial_references("FactoryFinder");
                    showStatus("Obtained Factory Finder ObjRef from Bootstrap Object");
                    FactoryFinder Ff = FactoryFinderHelper.narrow(Off);
      
                    // Find Factory by id
                    org.omg.CORBA.Object Of =
                        Ff.find_one_factory_by_id(UniversityS.RegistrarFactoryHelper.id());
                    UniversityS.RegistrarFactory F = UniversityS.RegistrarFactoryHelper.narrow(Of);
                    showStatus("Obtained RegistrarFactoryObjRef from FactoryFinder");

                    // Ask the "RegistrarFactory" to create a Registrar object
                    gRegistrarObjRef = F.find_registrar();
                    showStatus("Obtained Registrar ObjRef from Registrar Factory");
      
                    if (gRegistrarObjRef == null)
                    {
                        System.err.println("factory returned nil");
                        System.exit(1);
                    }

                    if (!getStudentDetails())
                    {
                        showStatus("Invalid Student Id");

                        // We logged in but have the wrong id so log off and
                        // have them try again
                        try
                        {
                            // log off the system
                            gPrinAuthObjRef.logoff();
                        }
                        catch (org.omg.CORBA.SystemException se)
                        {
                            System.err.println("CORBA Exception  " + se);
                            System.exit(1);
                        }
                        LogOnLabel.setVisible(false);
                        clearLogWarningLabels();
                        LogInvalidIdLabel.setVisible(true);
                        LogPanel.setLocation(1,1);
                        LogPanel.setVisible(true);
                        return;
                    }

                    // Okay, put up the synopsis information pane
                    SynopsisPanel.setLocation(1,1);
                    SynopsisPanel.setVisible(true);
                }
                catch(org.omg.CosLifeCycle.NoFactory e)
                {
                    System.err.println("No factory " + e);
                    System.exit(1);
                }
                catch(com.beasys.Tobj.InvalidName e)
                {
                    System.err.println("Invalid name: " + e);
                    System.exit(1);
                }
                catch(com.beasys.Tobj.CannotProceed e)
                {
                    System.err.println("Cannot proceed: "+ e);
                    System.exit(1);
                }
                catch(com.beasys.Tobj.RegistrarNotAvailable e)
                {
                    System.err.println("No Registrar " + e);
                    System.exit(1);
                }
                catch(org.omg.CORBA.SystemException e)
                {
                    System.err.println("System exception " + e);
                    System.exit(1);
                }
            }
            else
            {
                // We were not able to log in, have them try
                // again
                LogOnLabel.setVisible(false);
                LogInvalidPassLabel.setVisible(true);
                LogPanel.setLocation(1,1);
                LogPanel.setVisible(true);
            }

            
        }
        catch(org.omg.CORBA.SystemException e)
        {
            System.err.println("System exception " + e);
            System.exit(1);
        }

    }
    void log_off()
    {
        try
        {
            // log off the system
            gPrinAuthObjRef.logoff();
        }
        catch (org.omg.CORBA.SystemException e)
        {
            System.err.println("CORBA Exception  " + e);
        }
        System.exit(0);  
    }
    
    
    String get_default_server()
    {
        URL    u = getDocumentBase();
        return u.getHost();
    }


        //{{DECLARE_CONTROLS
	java.awt.Panel SynopsisPanel;
	java.awt.Label SynopsisCriteriaLabel;
	java.awt.Button SynopsisShowBtn;
	java.awt.Button SynopsisDetailsBtn;
	java.awt.TextField SynopsisCriteriaTextFld;
	java.awt.List SynopsisCourseList;
	java.awt.Panel SynopsisHeadingPanel;
	java.awt.Label SynopsisHeadingNumLabel;
	java.awt.Label SynopsisHeadingNameLabel;
	java.awt.Button SynopsisLogOffBtn;
	java.awt.Panel DetailsPanel;
	java.awt.Button DetailsPrevBtn;
	java.awt.Button DetailsNextBtn;
	java.awt.Button DetailsCloseBtn;
	java.awt.Panel DetailsDescPanel;
	java.awt.Label DetailsDescLabel;
	java.awt.TextArea DetailsDescTextArea;
	java.awt.Panel DetailsInfoPanel;
	java.awt.Label DetailsInfoIdLabel;
	java.awt.Label DetailsInfoIdValueLabel;
	java.awt.Label DetailsInfoProfessorLabel;
	java.awt.Label DetailsInfoProfessorValueLabel;
	java.awt.Label DetailsInfoCreditsLabel;
	java.awt.Label DetailsInfoCreditsValueLabel;
	java.awt.Label DetailsInfoCostLabel;
	java.awt.Label DetailsInfoCostValueLabel;
	java.awt.Label DetailsInfoOpenLabel;
	java.awt.Label DetailsInfoOpenValueLabel;
	java.awt.Label DetailsInfoTitleLabel;
	java.awt.Label DetailsInfoTitleValueLabel;
	java.awt.Label DetailsInfoSchedLabel;
	java.awt.Label DetailsInfoSchedTimeLabel;
	java.awt.Label DetailsInfoMonLabel;
	java.awt.Label DetailsInfoTueLabel;
	java.awt.Label DetailsInfoWedLabel;
	java.awt.Label DetailsInfoThuLabel;
	java.awt.Label DetailsInfoFriLabel;
	java.awt.Label DetailsInfoDurationValueLabel;
	java.awt.Label DetailsInfoDurationLabel;
	java.awt.Label InitializingLabel;
	java.awt.Label LogOnLabel;
	java.awt.Panel LogPanel;
	java.awt.Label LogStudentIdLabel;
	java.awt.Button LogOnBtn;
	java.awt.TextField LogStudentIdTextFld;
	java.awt.Label LogDomainPassLabel;
	java.awt.TextField LogDomainPassTextFld;
	java.awt.Label LogStudentPassLabel;
	java.awt.TextField LogStudentPassTextFld;
	java.awt.Label LogWelcomeLabel;
	java.awt.Label LogInvalidPassLabel;
	java.awt.Label LogInvalidPassLenLabel;
	java.awt.Label LogNonNumericIdLabel;
	java.awt.Label LogInvalidIdLabel;
	//}}

    class SymMouse extends java.awt.event.MouseAdapter
    {
        public void mousePressed(java.awt.event.MouseEvent event)
        {
            Object object = event.getSource();
            if (object == SynopsisLogOffBtn)
                SynopsisLogOffBtn_MousePress(event);
        }

        public void mouseExited(java.awt.event.MouseEvent event)
        {
            Object object = event.getSource();
            if (object == DetailsPrevBtn)
                showStatus("");
            else if (object == DetailsNextBtn)
                showStatus("");
            else if (object == DetailsCloseBtn)
                showStatus("");
            else if (object == SynopsisDetailsBtn)
                showStatus("");
            else if (object == SynopsisShowBtn)
                showStatus("");
        }

        public void mouseEntered(java.awt.event.MouseEvent event)
        {
            Object object = event.getSource();
            if (object == DetailsPrevBtn)
                showStatus("Show details for previous course");
            else if (object == DetailsNextBtn)
                showStatus("Show details for next course");
            else if (object == DetailsCloseBtn)
                showStatus("Go back to Course Synopsis screen");
            else if (object == SynopsisDetailsBtn)
                showStatus("Show details for selected courses");
            else if (object == SynopsisShowBtn)
                showStatus("Show synopsis for courses matching criteria");
            else if (object == LogOnBtn)
                showStatus("Attempt to Log On using supplied id and password");
        }

        public void mouseClicked(java.awt.event.MouseEvent event)
        {
            Object object = event.getSource();
            if (object == SynopsisShowBtn)
               SynopsisShowBtn_MouseClick(event);
            else if (object == SynopsisDetailsBtn)
                SynopsisDetailsBtn_MouseClick(event);
            else if (object == DetailsCloseBtn)
                DetailsPanelCloseButton_MouseClick(event);
            else if (object == DetailsNextBtn)
                NextButton_MouseClick(event);
            else if (object == DetailsPrevBtn)
                PrevButton_MouseClick(event);
            else if (object == LogOnBtn)
                LogOnButton_MouseClick(event);
        }
    }

    void SynopsisShowBtn_MouseClick(java.awt.event.MouseEvent event)
    {
        showSynopsisList();
    }

    class SymAction implements java.awt.event.ActionListener
    {
        public void actionPerformed(java.awt.event.ActionEvent event)
        {
            Object object = event.getSource();
            if (object == SynopsisCriteriaTextFld)
                SynopsisCriteriaTextFld_EnterHit(event);
        }
    }


    class SymText implements java.awt.event.TextListener
    {
        public void textValueChanged(java.awt.event.TextEvent event)
        {
            Object object = event.getSource();
            if (object == SynopsisCriteriaTextFld)
                    SynopsisCriteriaTextFld_TextValueChanged(event);
            else if (object == LogStudentIdTextFld)
                    LogStudentIdTextFld_TextValueChanged(event);
            else if (object == LogDomainPassTextFld)
                    LogDomainPassTextFld_TextValueChanged(event);
            else if (object == LogStudentPassTextFld)
                    LogStudentPassTextFld_TextValueChanged(event);
        }
    }

    void SynopsisCriteriaTextFld_TextValueChanged(java.awt.event.TextEvent event)
    {
        SynopsisShowBtn.setEnabled(SynopsisCriteriaTextFld.getText().length() != 0);
    }

    void LogStudentIdTextFld_TextValueChanged(java.awt.event.TextEvent event)
    {
        LogOnBtn.setEnabled(LogStudentIdTextFld.getText().length() != 0);
    }

    void LogDomainPassTextFld_TextValueChanged(java.awt.event.TextEvent event)
    {
        LogOnBtn.setEnabled(LogDomainPassTextFld.getText().length() != 0);
    }

    void LogStudentPassTextFld_TextValueChanged(java.awt.event.TextEvent event)
    {
        LogOnBtn.setEnabled(LogStudentPassTextFld.getText().length() != 0);
    }

    class SymItem implements java.awt.event.ItemListener
    {
        public void itemStateChanged(java.awt.event.ItemEvent event)
        {
            Object object = event.getSource();
            if (object == SynopsisCourseList)
                    CourseSynopsisList_ItemStateChanged(event);
        }
    }

    void CourseSynopsisList_ItemStateChanged(java.awt.event.ItemEvent event)
    {
        if ((SynopsisCourseList.getSelectedIndexes()).length != 0)
            SynopsisDetailsBtn.setEnabled(true);
        else
            SynopsisDetailsBtn.setEnabled(false);

    }



    class SymKey extends java.awt.event.KeyAdapter
    {
        public void keyPressed(java.awt.event.KeyEvent event)
        {
            // We want to trap if they hit the enter key while focus is
            // on a button
            if ( event.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            {
                Object object = event.getSource();
                if (object == SynopsisShowBtn)
                    SynopsisShowBtn_KeyPress(event);
                else if (object == DetailsNextBtn)
                    DetailsNextBtn_KeyPress(event);
                else if (object == DetailsPrevBtn)
                    DetailsPrevBtn_KeyPress(event);
                else if (object == DetailsCloseBtn)
                    DetailsCloseBtn_KeyPress(event);
                else if (object == LogOnBtn)
                    LogOnButton_KeyPress(event);
            }
        }
    }

    void SynopsisShowBtn_KeyPress(java.awt.event.KeyEvent event)
    {
        showSynopsisList();
    }

    void SynopsisCriteriaTextFld_EnterHit(java.awt.event.ActionEvent event)
    {
        showSynopsisList();
    }

    void SynopsisDetailsBtn_MouseClick(java.awt.event.MouseEvent event)
    {
        if (SynopsisDetailsBtn.isEnabled())
           showDetails();
    }

    void showSynopsisList()
    {
        fillCourseSynopsisList();
        SynopsisCourseList.setEnabled(true);
    }


    
    
    /**
     * Fills in the visual course synopsis list based on the search
     * criteria string entered by the user.  A call is made to
     * getCourseSynopsisFromServer which interacts with the 
     * server to return a list of course synopsis
     *
     */
    void fillCourseSynopsisList()
    {
        boolean found_something = false;
        String search_string = SynopsisCriteriaTextFld.getText();

        SynopsisCourseList.setVisible(false);
        SynopsisCourseList.setEnabled(false);
        SynopsisCourseList.removeAll();
        int row = 0;

        UniversityS.CourseSynopsis[] course_synopsis =
                                getCourseSynopsisFromServer( search_string);

        // If we got something back
        if (course_synopsis != null)
        {
            // add them to the CourseList
            for (int index = 0; index < course_synopsis.length; index++)
            {
                Integer course_number = new Integer(course_synopsis[index].course_number);
                SynopsisCourseList.add( course_number.toString() +
                                    "                            " +
                                    course_synopsis[index].title);
                if (!found_something)
                    found_something = true;
            }
        }

        if (found_something)
        {
                    SynopsisCourseList.setVisible(true);
                    SynopsisCourseList.setEnabled(true);
        }
        else
           SynopsisDetailsBtn.setEnabled(false);
    }


    
    /**
     * Gets the course synopsis from the server in chunks using an
     * enumerator as necessary.
     *
     * @param aCriteria     The search criteria entered by the user. This
     *                      criteria is used to selected which courses
     *                      should have a synopsis displayed.
     *
     * @return UniversityS.CourseSynopsis[] An array of UniversityS.CourseSynopsis
     *                      returned by the server.
     *
     */
    UniversityS.CourseSynopsis[] getCourseSynopsisFromServer( String aCriteria)
    {

        UniversityS.CourseSynopsis[] course_synopsis_chunks = null;
        UniversityS.CourseSynopsis[] chunk_course_synopsis_from_server = null;
        final int CHUNK_SIZE = 10;
        int total_fetched = 0;
        int num_to_fetch = 0;

        org.omg.CORBA.IntHolder number_remaining = new org.omg.CORBA.IntHolder();
        UniversityS.CourseSynopsisEnumeratorHolder enumerate_the_rest =
                        new UniversityS.CourseSynopsisEnumeratorHolder();

        try
        {
            // Do the invoke on the Registrar object to get the
            // courses from the server
            chunk_course_synopsis_from_server =
                        gRegistrarObjRef.get_courses_synopsis(
                                                aCriteria,
                                                CHUNK_SIZE,
                                                number_remaining,
                                                enumerate_the_rest);

            
            num_to_fetch = number_remaining.value;

            // This is the array for our first chunk of course synopsis
            course_synopsis_chunks =
                          new UniversityS.CourseSynopsis[chunk_course_synopsis_from_server.length];

            total_fetched = chunk_course_synopsis_from_server.length;
            showStatus("Obtained " + total_fetched + " Course Synopsis from server");


            // Save the first chunk of course synopsis
            for (int index = 0;index < chunk_course_synopsis_from_server.length; index++)
            {
                course_synopsis_chunks[index] =
                                    chunk_course_synopsis_from_server[index];
            }

        }
        catch(org.omg.CORBA.SystemException cse)
        {
            System.err.println(cse);
            System.err.println("Failed getting the course synopsis from the server");
        }

        try
        {
            // As long as there are more chunks to fetch from the server
            while (num_to_fetch != 0)
            {

                // Get the next chunk
                chunk_course_synopsis_from_server =
                        enumerate_the_rest.value.get_next_n(CHUNK_SIZE, number_remaining);

                num_to_fetch = number_remaining.value;
                
                total_fetched = total_fetched +
                                        chunk_course_synopsis_from_server.length;
                showStatus("Obtained " + total_fetched + " course synopsis from server");

                // we already have a least one chunk so we have to allocate
                // a new array that can contain the existing chunks and the
                // chunk we just got.

                // Figure out how big our new chunks length will need to be
                int new_chunks_length = course_synopsis_chunks.length +
                                        chunk_course_synopsis_from_server.length;

                // Allocate a new array big enough to hold the chunks we had
                // and the new chunk we just fetched
                UniversityS.CourseSynopsis[] temp_course_synopsis_chunks =
                          new UniversityS.CourseSynopsis[new_chunks_length];

                int index = 0;
                // copy the chunks we already had into the new array
                for (;index < course_synopsis_chunks.length; index++)
                {
                    temp_course_synopsis_chunks[index] =
                                course_synopsis_chunks[index];
                }

                // Okay, we've grabbed our existing chunks, now add the chunk
                // we just got from the server
                for (int j = 0;index < new_chunks_length; index++, j++)
                {
                    temp_course_synopsis_chunks[index] = new UniversityS.CourseSynopsis(
                                chunk_course_synopsis_from_server[j].course_number,
                                chunk_course_synopsis_from_server[j].title);
       
                }

                // We want course_synopsis_chunks to be our official
                // chunks array
                course_synopsis_chunks = temp_course_synopsis_chunks;

                // All done with this temporary one
                temp_course_synopsis_chunks = null;
            } // while
        } // try
        catch(org.omg.CORBA.SystemException cse)
        {
            System.err.println(cse);
            System.err.println("Failed getting the course synopsis from the server");
        }

        // Save away the chunks array we created
        gCourseSynopsis = course_synopsis_chunks;

        // Tell the server it can get rid of the enumerator
        if (enumerate_the_rest.value != null)
            enumerate_the_rest.value.destroy();

        // Done with this local chunk array
        chunk_course_synopsis_from_server = null;

        return gCourseSynopsis;
    }


    
    /**
     * Figures out which courses the user has selected in the
     * visible course synopsis list, creates a list of course numbers
     * and then calls getCourseDetailsFromServer() to actually go off and
     * get the course details from the server.
     */
    void showDetails()
    {
        // At the onset we don't know how many courses were selected by
        // the user, so we create an array equal in size to the array
        // of course synopsis and then figure out how many courses were
        // actually selected in order to pass an array exactly equal
        // in size to the number selected.
        int[] big_selected_course_numbers = new int[gCourseSynopsis.length];
        for (int index = 0; index < gCourseSynopsis.length; index++)
            big_selected_course_numbers[index] = 0;

        // Loop through the array of CourseSynopsis objects
        int num_visible = 0;
        int index_selected = 0;
        for (int index = 0; index < gCourseSynopsis.length; index++)
        {
            // We've got a CourseSynopsis object that was put in the
            // CourseSynopsisList
            if (SynopsisCourseList.isIndexSelected( num_visible))
            {
                // and, it was selected by the user so add it to the
                // details frame
                big_selected_course_numbers[index_selected] = (gCourseSynopsis[index]).course_number;
                index_selected++;
            }
            num_visible++;
        }

        // Unfortunately, we created the selected_course_numbers array based
        // on the size of the gCourseSynopsis array. Unless the
        // user selected all of the courses we'll have some null entries in the
        // array. These nulls will make life complicated later on so we need
        // to do the equivalent of a realloc() here.  It shouldn't be too
        // much of a performance hit.

        int count = 0;
        for (; count < big_selected_course_numbers.length; count++)
        {
            if (big_selected_course_numbers[count] == 0)
                // If this isn't an integer it is a 0 which means we're
                // done
                break;
        }

        // OK we know how many (non-null) entries  we have
        int[] selected_course_numbers = new int[count];

        // Make a new array with no nulls in it
        for (int index = 0; index < count; index++)
        {
            selected_course_numbers[index] = big_selected_course_numbers[index];
        }

        getCourseDetailsFromServer( selected_course_numbers );

        SynopsisPanel.setVisible(false);
        // We have it elsewhere so we can debug it in a Dev Env
        // at run time we move it to where it should be
        DetailsPanel.setLocation(1,1);
        DetailsPanel.setVisible(true);
    }

    /**
     * Figures out how to obtain chunks of Course Details from
     * the server and then does it.  We do it in chunks so that we don't
     * stress the Java Orb and get marshalling errors.
     *
     * @param aSelectedCourseNumbers    An array of ints containing
     *                              the course numbers of the course
     *                              synopsis that the user selected.
     *
     */
    void getCourseDetailsFromServer( int[] aSelectedCourseNumbers)
    {
        // Contains the last chunk we got from the server
        UniversityS.CourseDetails[] chunk_details_from_server = null;

        // Contains all the chunks we've gotten
        UniversityS.CourseDetails[] chunks_in_hand = null;

        // The size of a normal "full" chunk.
        final int CHUNK_SIZE = 5;

        // Number of courses about which the user wanted details
        int total_selected = aSelectedCourseNumbers.length;

        // Figure out how many chunks we will need to get
        int chunks_to_get = (total_selected/CHUNK_SIZE) + 1;
        int partial_chunk_size = 0;
        for (int chunk_count = 0; chunk_count < chunks_to_get; chunk_count++)
        {
            int[] selected_course_numbers_chunk_array;
            int current_chunk_size = 0;

            // Should we get a full size chunk or a partial chunk?
            if ((chunk_count + 1) * CHUNK_SIZE < total_selected)
            {
                // We've got an entire chunk to get
                current_chunk_size = CHUNK_SIZE;
            }
            else
            {
                // We've got a partial chunk to get
                partial_chunk_size = total_selected - (chunk_count * CHUNK_SIZE);
                current_chunk_size = partial_chunk_size;
            }


            // Fill in our selected course numbers chunk
            selected_course_numbers_chunk_array = new int[current_chunk_size];
            for (int i = 0; i < current_chunk_size; i++)
            {
                selected_course_numbers_chunk_array[i] =
                                aSelectedCourseNumbers[i + (chunk_count * CHUNK_SIZE)];
            }

            try
            {
                // Do the invoke on the Registrar object to get the
                // details from the server
                chunk_details_from_server =
                    gRegistrarObjRef.get_courses_details(
                            selected_course_numbers_chunk_array );
            }
            catch(org.omg.CORBA.SystemException e)
            {
                System.err.println(e);
                System.err.println("Unable to get course details from server");
            }
            
            int total_fetched = ((chunk_count + 1) * CHUNK_SIZE) + partial_chunk_size;
            showStatus("Obtained " + total_fetched + "Course Details from server");

            // Figure out how many details we already have gotten in previous
            // chunks that we have to save
            int chunks_in_hand_length = 0;
            if (chunks_in_hand != null)
                chunks_in_hand_length = chunks_in_hand.length;

            // Figure out how many details we'll have when we add the details
            // we already got to the details we just fetched from the server
            int new_chunks_length = chunks_in_hand_length +
                                        chunk_details_from_server.length;

            // Make a new temporary chunks array to hold everything
            UniversityS.CourseDetails[] temp_details_chunks =
                            new UniversityS.CourseDetails[new_chunks_length];

            // Do we need to save away any existing chunks?
            int new_chunks_index = 0;
            if (chunks_in_hand_length != 0)
            {
                // Yes, save away the chunks of details we already had
                for (; new_chunks_index < chunks_in_hand_length; new_chunks_index++)
                    temp_details_chunks[new_chunks_index] =
                                            chunks_in_hand[new_chunks_index];
            }

            // Now add the chunk of details we just got from the server
            for (int j = 0; new_chunks_index < new_chunks_length; new_chunks_index++, j++)
                temp_details_chunks[new_chunks_index] = chunk_details_from_server[j];

            // Hold on to our new bigger chunks array
            chunks_in_hand = temp_details_chunks;
            temp_details_chunks = null;
            selected_course_numbers_chunk_array = null;
        } // for
        
        gCourseDetailsFromSrvr = chunks_in_hand;
        chunks_in_hand = null;
        
        // We're at the first course in the details list
        gCurrentDetailsIndex = 0;

        // Display the details for the first course selected
        // by the user
        fillDetailsPanel( gCourseDetailsFromSrvr[0] );

        // We know that there won't be any previous courses to start since
        // we're starting at the first course
        DetailsPrevBtn.setEnabled(false);

        // We want to make sure that the Next button is set correctly
        // when we show the details for the first course the user selected.
        if (gCourseDetailsFromSrvr.length > 1)
            DetailsNextBtn.setEnabled(true);
        else
            DetailsNextBtn.setEnabled(false);
    }


    /**
     * Fills in the details panel with the information for a particular
     * course which is passed in to it.
     *
     * @param aDetailsForCourse Contains details on one course
     */
    void fillDetailsPanel( UniversityS.CourseDetails aDetailsForCourse)
    {
        // Fill in the information in the Details Info panel
        DetailsInfoIdValueLabel.setText( (new Integer(aDetailsForCourse.course_number).toString()));
        DetailsInfoProfessorValueLabel.setText( aDetailsForCourse.professor);
        DetailsInfoTitleValueLabel.setText( aDetailsForCourse.title);
        Float f_bal = new Float(aDetailsForCourse.cost);
        DetailsInfoCostValueLabel.setText( "$" + f_bal.toString());
        DetailsInfoCreditsValueLabel.setText( (new Integer(aDetailsForCourse.number_of_credits).toString()));
        //if ( aDetailsForCourse.number_of_seats > aDetailsForCourse.number_of_registered_students)
            DetailsInfoOpenValueLabel.setText( "yes");
        //else
          //  DetailsInfoOpenValueLabel.setText( "closed");


        // Do the schedule stuff, start time, duration, days of the week
        int start_hours = aDetailsForCourse.class_schedule.start_hour;
        String start_time = new Integer(start_hours).toString() +
                                            ":00";
        DetailsInfoSchedTimeLabel.setText(start_time);

        int duration_hours = aDetailsForCourse.class_schedule.duration/60;
        int duration_minutes = aDetailsForCourse.class_schedule.duration -
                                    (duration_hours * 60);
        String string_duration_minutes;
        if (duration_minutes == 0)
            string_duration_minutes = "00";
        else
            string_duration_minutes = new Integer(duration_minutes).toString();
        String duration_time = new Integer(duration_hours).toString() +
                                            ":" + string_duration_minutes;
        DetailsInfoDurationValueLabel.setText(duration_time);

        if ((aDetailsForCourse.class_schedule.class_days & UniversityS.MONDAY.value) != 0)
            DetailsInfoMonLabel.setForeground(gPurpleColor);
        else
            DetailsInfoMonLabel.setForeground(gGrayColor);

        if ((aDetailsForCourse.class_schedule.class_days & UniversityS.TUESDAY.value) != 0)
            DetailsInfoTueLabel.setForeground(gPurpleColor);
        else
            DetailsInfoTueLabel.setForeground(gGrayColor);

        if ((aDetailsForCourse.class_schedule.class_days & UniversityS.WEDNESDAY.value) != 0)
            DetailsInfoWedLabel.setForeground(gPurpleColor);
        else
            DetailsInfoWedLabel.setForeground(gGrayColor);

        if ((aDetailsForCourse.class_schedule.class_days & UniversityS.THURSDAY.value) != 0)
            DetailsInfoThuLabel.setForeground(gPurpleColor);
        else
            DetailsInfoThuLabel.setForeground(gGrayColor);

        if ((aDetailsForCourse.class_schedule.class_days & UniversityS.FRIDAY.value) != 0)
            DetailsInfoFriLabel.setForeground(gPurpleColor);
        else
            DetailsInfoFriLabel.setForeground(gGrayColor);

        // Fill in the description of the course
        DetailsDescTextArea.setText( aDetailsForCourse.description);
    }


    void NextButton_MouseClick(java.awt.event.MouseEvent event)
    {
        nextDetails();
    }

    // Handle stuff for the Next Button in the Details Panel
    void nextDetails()
    {
        if (gCurrentDetailsIndex < gCourseDetailsFromSrvr.length - 1)
        {
            gCurrentDetailsIndex++;
            fillDetailsPanel( gCourseDetailsFromSrvr[gCurrentDetailsIndex]);

            DetailsPrevBtn.setEnabled(true);

            // Make sure we don't walk off the end
            if (gCurrentDetailsIndex >= gCourseDetailsFromSrvr.length - 1)
            {
                DetailsNextBtn.setEnabled(false);
            }

        }
    }

    void PrevButton_MouseClick(java.awt.event.MouseEvent event)
    {
        previousDetails();
    }

    // Handle stuff for the Prev Button in the Details Panel
    void previousDetails()
    {
        // There is at least one more
        if (gCurrentDetailsIndex > 0)
        {
            gCurrentDetailsIndex--;
            fillDetailsPanel( gCourseDetailsFromSrvr[gCurrentDetailsIndex]);

            DetailsNextBtn.setEnabled(true);

            // Make sure we don't walk off the end
            if (gCurrentDetailsIndex == 0)
            {
                DetailsPrevBtn.setEnabled(false);
            }

        }

    }

    void DetailsPanelCloseButton_MouseClick(java.awt.event.MouseEvent event)
    {
        closeDetails();
    }

    // Do stuff for the Close Button in the Details Panel
    void closeDetails()
    {
        DetailsPanel.setVisible(false);
        SynopsisPanel.setVisible(true);
    }

    void DetailsNextBtn_KeyPress(java.awt.event.KeyEvent event)
    {
        nextDetails();
    }

    void DetailsPrevBtn_KeyPress(java.awt.event.KeyEvent event)
    {
        previousDetails();
    }

    void DetailsCloseBtn_KeyPress(java.awt.event.KeyEvent event)
    {
        closeDetails();
    }



    // Get student details
    boolean getStudentDetails()
    {
        int student_id = Integer.parseInt (gUserId.toString());
        boolean valid_id = true;
        try
        {
            // Do the invoke on the Registrar object to get the
            // student details
            gStudentDetails = 
                gRegistrarObjRef.get_student_details(student_id);
        }
        catch(org.omg.CORBA.OBJ_ADAPTER e)
        {
            valid_id = false;
        }
        catch(org.omg.CORBA.NO_IMPLEMENT e)
        {
            valid_id = false;
        }
        catch(org.omg.CORBA.BAD_PARAM e)
        {
            valid_id = false;
        }
        catch(org.omg.CORBA.SystemException e)
        {
            valid_id= false;
            System.err.println("System exception " + e);
            System.exit(1);
        }

        return valid_id;
    }

    void LogOnButton_MouseClick(java.awt.event.MouseEvent event)
    {
        log_on();
    }

    void LogOnButton_KeyPress(java.awt.event.KeyEvent event)
    {
        log_on();
    }

    void SynopsisLogOffBtn_MousePress(java.awt.event.MouseEvent event)
    {
        log_off();
    }
}
