//	(c) 2003 BEA Systems, Inc. All Rights Reserved. 
//--------------------------------------------------------------------
//
// simple_i.h
//
// C++ servant declarations for the simpapp_par sample declaration.
//
// This file was originally generated by using the "-i" idl switch,
// then edited by hand.
//
// BEA Systems Inc. sample code
//
//--------------------------------------------------------------------

#ifndef _simple_i_h
#define _simple_i_h

#include "simple_s.h"

class Simple_i : public POA_Simple
{
  public:
    virtual char* to_lower(const char* val);
    virtual void  to_upper(char*&      val);
    virtual CORBA::Long s_pid();
};

#endif
